import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How much of the available area is used for housing?",
  "subtitle": "On average, 3.72% of the EU’s available land area is used for residential purposes. This represents a 28% increase compared with 2018.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0.028,FALSE,,,,,,,,,\nBelgium,BE,0.119,FALSE,,,,,,,,,\nBulgaria,BG,0.015,FALSE,,,,,,,,,\nCroatia,HR,0.020,FALSE,,,,,,,,,\nCyprus,CY,0.036,FALSE,,,,,,,,,\nCzechia,CZ,0.037,FALSE,,,,,,,,,\nDenmark,DK,0.057,FALSE,,,,,,,,,\nEstonia,EE,0.019,FALSE,,,,,,,,,\nFinland,FI,0.013,FALSE,,,,,,,,,\nFrance,FR,0.046,FALSE,,,,,,,,,\nGermany,DE,0.048,FALSE,,,,,,,,,\nGreece,EL,0.016,FALSE,,,,,,,,,\nHungary,HU,0.036,FALSE,,,,,,,,,\nIreland,IE,0.027,FALSE,,,,,,,,,\nItaly,IT,0.038,FALSE,,,,,,,,,\nLatvia,LV,0.020,FALSE,,,,,,,,,\nLithuania,LT,0.024,FALSE,,,,,,,,,\nLuxembourg,LU,0.037,FALSE,,,,,,,,,\nMalta,MT,0.149,FALSE,,,,,,,,,\nNetherlands,NL,0.069,FALSE,,,,,,,,,\nPoland,PL,0.036,FALSE,,,,,,,,,\nPortugal,PT,0.023,FALSE,,,,,,,,,\nRomania,RO,0.018,FALSE,,,,,,,,,\nSlovakia,SK,0.025,FALSE,,,,,,,,,\nSlovenia,SI,0.025,FALSE,,,,,,,,,\nSpain,ES,0.012,FALSE,,,,,,,,,\nSweden,SE,0.012,FALSE,,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.028,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.119,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.015,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.02,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.036,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.037,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.057,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.019,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.013,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.046,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.048,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.016,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.036,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.027,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.038,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.02,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.024,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.037,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.149,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.069,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.036,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.023,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.018,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.025,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.025,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.012,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.012,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red-purple",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat (2022)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Residential housing includes residential gardens.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/lan_use_ovw/bookmark/table?lang=en&bookmarkId=c3b2713c-392d-4232-9c4a-dd088c0e31c8&c=1757071412000",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "used for residential purposes",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How much of the available area is used for housing?",
    "subtitle": "On average, 3.72% of the EU’s available land area is used for residential purposes. This represents a 28% increase compared with 2018.",
    "textNoteDescription": "Note",
    "textNote": "Residential housing includes residential gardens.",
    "textSourceDescription": "Source",
    "textSource": "Eurostat (2022)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here"
  },
  "clusters": [],
  "colorScale": null
});